name: CI

on: [push, pull_request]

jobs:
  format:
    name: Code Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: yarn install
      - name: Run code formatting check
        run: yarn run check
